# Generated by Django 5.0.3 on 2024-03-08 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=100)),
                ('grupo_curso', models.CharField(max_length=50)),
                ('anio_curso', models.IntegerField()),
                ('fecha_creacion_curso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_estudiante', models.CharField(max_length=20)),
                ('nombres_estudiante', models.CharField(max_length=100)),
                ('apellidos_estudiante', models.CharField(max_length=100)),
                ('correo_estudiante', models.EmailField(max_length=254)),
                ('contrasenia_estudiante', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_profesor', models.CharField(max_length=20)),
                ('nombres_profesor', models.CharField(max_length=100)),
                ('apellidos_profesor', models.CharField(max_length=100)),
                ('correo_profesor', models.EmailField(max_length=254)),
                ('contrasenia_profesor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstudiantesCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cursos')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estudiantes')),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='profesor_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.profesores'),
        ),
    ]
