# Generated by Django 5.0.3 on 2024-03-08 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_estudiantes_user_profesores_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='contrasenia_estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='correo_estudiante',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='contrasenia_profesor',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='correo_profesor',
        ),
    ]
