# Generated by Django 5.0.3 on 2024-03-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_estudiantes_contrasenia_estudiante_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grupo',
            new_name='Grupos',
        ),
    ]
