# Generated by Django 5.0.3 on 2024-03-09 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_grupo_grupos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanesEstudio',
            fields=[
                ('id_plan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_plan', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='semestre_curso',
            field=models.CharField(choices=[('1S', '1S'), ('2S', '2S')], default='1S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='plan_estudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.planesestudio'),
        ),
    ]
