# Generated by Django 5.0.3 on 2024-03-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_planesestudio_cursos_semestre_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estudiantes')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.grupos')),
            ],
        ),
        migrations.AddField(
            model_name='grupos',
            name='estudiantes_grupo',
            field=models.ManyToManyField(through='myapp.Inscripcion', to='myapp.estudiantes'),
        ),
        migrations.DeleteModel(
            name='EstudiantesCursos',
        ),
    ]
