# Generated by Django 5.0.3 on 2024-03-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_inscripcion_grupos_estudiantes_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
