# Generated by Django 5.0.3 on 2024-03-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_inscripcion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.grupos')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_estudiante',
            fields=[
                ('id_asistencia_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('registro_Asistencia', models.BooleanField(default=False)),
                ('excusa', models.BooleanField(default=False, null=True)),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.asistencia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estudiantes')),
            ],
        ),
    ]
