# Generated by Django 5.0.3 on 2024-03-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_asistencia_fecha_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excusa_falta_estudiante',
            fields=[
                ('id_excusa', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=100)),
                ('fecha_creacion_excusa', models.DateTimeField(auto_now_add=True)),
                ('asistencia_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.asistencia_estudiante')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estudiantes')),
            ],
        ),
    ]
