# Generated by Django 5.0.3 on 2024-03-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_excusa_falta_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='excusa_falta_estudiante',
            name='soporte_excusa',
            field=models.FileField(blank=True, null=True, upload_to='soportes_excusas/'),
        ),
    ]
