# Generated by Django 5.0.3 on 2024-03-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_excusa_falta_estudiante_soporte_excusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
