# Generated by Django 5.0.3 on 2024-03-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_asistencia_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='excusa_falta_estudiante',
            name='excusa_valida',
            field=models.BooleanField(default=False),
        ),
    ]
