# Generated by Django 5.0.3 on 2024-04-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='excusa_falta_estudiante',
            name='motivo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='excusa_falta_estudiante',
            name='soporte_excusa',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='grupos',
            name='nombre_grupo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
